source 'https://github.com/CocoaPods/Specs.git'

target 'HLLibrary', :exclusive => true do
  pod "HLLibrary", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "HLLibrary", :path => "../"

  
end
